### ISSUE TITLE
Create mongoose schemas and data models for your resources

### ISSUE THREAD

**Issue by ecasilla** [JMHill/capstone#2]
- [x] User model
- [x] Place model
- [x] List model

**Comment by JMHill** [comment]
![new doc 8_1](https://cloud.githubusercontent.com/assets/6236708/8198543/102d24fa-1476-11e5-8036-8513b26ed9c1.jpg)

@ecasilla I read up on domain/data modeling a bit in this article: http://agiledata.org/essays/agileDataModeling.html and reattempted a domain model. If you have any other reading/resources that could help me out, just let me know. Gonna start on the mongoose models/schemas shortly.
